export const adminTypes = {
  // Dashboard type
  GET_PRODUCT_LISTING_DATA_PENDING: "GET_PRODUCT_LISTING_DATA_PENDING",
  GET_PRODUCT_LISTING_DATA_SUCCESS: "GET_PRODUCT_LISTING_DATA_SUCCESS",
  GET_PRODUCT_LISTING_DATA_FAILED: "GET_PRODUCT_LISTING_DATA_FAILED",

  GET_PRODUCT_DETAILS_DATA_PENDING: "GET_PRODUCT_DETAILS_DATA_PENDING",
  GET_PRODUCT_DETAILS_DATA_SUCCESS: "GET_PRODUCT_DETAILS_DATA_SUCCESS",
  GET_PRODUCT_DETAILS_DATA_FAILED: "GET_PRODUCT_DETAILS_DATA_FAILED",
};
